version: '3'
services:
  dev:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/code
    ports:
        - 4000:4000
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
    phoenix_code:
